*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 00:34:47 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x200e050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
[uwsgi-signal] signum 99 registered (wid: 0 modifier1: 0 target: default, any worker)
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x200e050 pid: 12095 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12095)
spawned uWSGI worker 1 (pid: 12098, cores: 1)
spawned uWSGI worker 2 (pid: 12099, cores: 1)
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 00:57:55 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8d5050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
[uwsgi-signal] signum 99 registered (wid: 0 modifier1: 0 target: default, any worker)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8d5050 pid: 12165 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12165)
spawned uWSGI worker 1 (pid: 12168, cores: 1)
spawned uWSGI worker 2 (pid: 12169, cores: 1)
[pid: 12169|app: 0|req: 1/1] 123.157.213.14 () {40 vars in 631 bytes} [Tue Apr 21 00:57:58 2015] GET / => generated 21 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
start working
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/GitRepo1/yugi/2
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (/home/GitRepo1/yugi/2/app_uwsgi.sock)
running /home/GitRepo1/yugi/2/venv/bin/uwsgi
[uWSGI] getting INI configuration from /home/GitRepo1/yugi/2/app_uwsgi.ini
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 01:12:13 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1b02f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
  File "/home/GitRepo1/yugi/2/app.py", line 262
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"]))):
                                                                                                            ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12165)
spawned uWSGI worker 1 (pid: 12194, cores: 1)
spawned uWSGI worker 2 (pid: 12195, cores: 1)
Tue Apr 21 01:12:23 2015 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Apr 21 01:12:23 2015 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 01:12:25 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1942050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
  File "/home/GitRepo1/yugi/2/app.py", line 262
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"]))):
                                                                                                            ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12207)
spawned uWSGI worker 1 (pid: 12208, cores: 1)
spawned uWSGI worker 2 (pid: 12209, cores: 1)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/GitRepo1/yugi/2
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (/home/GitRepo1/yugi/2/app_uwsgi.sock)
running /home/GitRepo1/yugi/2/venv/bin/uwsgi
[uWSGI] getting INI configuration from /home/GitRepo1/yugi/2/app_uwsgi.ini
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 01:13:30 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2529f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
  File "/home/GitRepo1/yugi/2/app.py", line 262
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"]))):
                                                                                                            ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12207)
spawned uWSGI worker 1 (pid: 12218, cores: 1)
spawned uWSGI worker 2 (pid: 12219, cores: 1)
Tue Apr 21 01:13:39 2015 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Apr 21 01:13:39 2015 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 01:13:46 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1aaa050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
  File "/home/GitRepo1/yugi/2/app.py", line 262
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"]))):
                                                                                                            ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12232)
spawned uWSGI worker 1 (pid: 12233, cores: 1)
spawned uWSGI worker 2 (pid: 12234, cores: 1)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/GitRepo1/yugi/2
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (/home/GitRepo1/yugi/2/app_uwsgi.sock)
running /home/GitRepo1/yugi/2/venv/bin/uwsgi
[uWSGI] getting INI configuration from /home/GitRepo1/yugi/2/app_uwsgi.ini
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 01:13:54 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1331f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
  File "/home/GitRepo1/yugi/2/app.py", line 262
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"]))):
                                                                                                            ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12232)
spawned uWSGI worker 1 (pid: 12242, cores: 1)
spawned uWSGI worker 2 (pid: 12243, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 12242|app: -1|req: -1/1] 123.157.213.247 () {32 vars in 391 bytes} [Tue Apr 21 01:13:55 2015] GET /api/token => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 12243|app: -1|req: -1/2] 123.157.213.14 () {38 vars in 601 bytes} [Tue Apr 21 01:13:57 2015] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Tue Apr 21 01:14:03 2015 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Apr 21 01:14:03 2015 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 01:14:21 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1970050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
  File "/home/GitRepo1/yugi/2/app.py", line 262
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"]))):
                                                                                                            ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12256)
spawned uWSGI worker 1 (pid: 12257, cores: 1)
spawned uWSGI worker 2 (pid: 12258, cores: 1)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/GitRepo1/yugi/2
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (/home/GitRepo1/yugi/2/app_uwsgi.sock)
running /home/GitRepo1/yugi/2/venv/bin/uwsgi
[uWSGI] getting INI configuration from /home/GitRepo1/yugi/2/app_uwsgi.ini
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 01:14:51 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1cb7f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
  File "/home/GitRepo1/yugi/2/app.py", line 328
    db.:create_all()
       ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12256)
spawned uWSGI worker 1 (pid: 12267, cores: 1)
spawned uWSGI worker 2 (pid: 12268, cores: 1)
Tue Apr 21 01:15:00 2015 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Apr 21 01:15:00 2015 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.10 (64bit) on [Tue Apr 21 01:15:20 2015] ***
compiled with version: 4.8.2 on 18 April 2015 15:12:58
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ2356z6vn9Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/GitRepo1/yugi/2
detected binary path: /home/GitRepo1/yugi/2/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/GitRepo1/yugi/2/app_uwsgi.sock fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
Set PythonHome to /home/GitRepo1/yugi/2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ba1050
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218280 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added /home/GitRepo1/yugi/2/ to pythonpath.
[uwsgi-signal] signum 99 registered (wid: 0 modifier1: 0 target: default, any worker)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1ba1050 pid: 12285 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12285)
spawned uWSGI worker 1 (pid: 12288, cores: 1)
spawned uWSGI worker 2 (pid: 12289, cores: 1)
[pid: 12289|app: 0|req: 1/1] 123.157.213.14 () {40 vars in 631 bytes} [Tue Apr 21 01:15:29 2015] GET / => generated 6 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
[pid: 12288|app: 0|req: 1/2] 123.157.213.247 () {32 vars in 391 bytes} [Tue Apr 21 01:15:58 2015] GET /api/token => generated 159 bytes in 145 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 12289|app: 0|req: 2/3] 123.157.213.247 () {30 vars in 368 bytes} [Tue Apr 21 01:16:03 2015] GET /api/favorite => generated 22441 bytes in 200 msecs (HTTP/1.1 200) 2 headers in 74 bytes (1 switches on core 0)
https://api.jd.com/routerjson?v=2.0&method=jingdong.ware.baseproduct.get&app_key=84F0963912EA9D56CD29E8EB3E774A2B&360buy_param_json={%22ids%22:%221217499%22,%22base%22:%22name%22}&timestamp=2015-04-21 01:18:07
{u'jingdong_ware_baseproduct_get_responce': {u'product_base': [{u'sku_id': 1217499, u'name': u'\u82f9\u679c\uff08Apple\uff09iPhone 6 (A1586) 16GB \u91d1\u8272 \u79fb\u52a8\u8054\u901a\u7535\u4fe14G\u624b\u673a', u'weight': 0}], u'code': u'0'}}
<type 'unicode'>
[pid: 12288|app: 0|req: 2/4] 123.157.213.247 () {32 vars in 427 bytes} [Tue Apr 21 01:18:07 2015] GET /api/jdproducts/name/1217499 => generated 133 bytes in 258 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
https://api.jd.com/routerjson?v=2.0&method=jingdong.ware.baseproduct.get&app_key=84F0963912EA9D56CD29E8EB3E774A2B&360buy_param_json={%22ids%22:%221217499%22,%22base%22:%22name%22}&timestamp=2015-04-21 01:18:18
{u'jingdong_ware_baseproduct_get_responce': {u'product_base': [{u'sku_id': 1217499, u'name': u'\u82f9\u679c\uff08Apple\uff09iPhone 6 (A1586) 16GB \u91d1\u8272 \u79fb\u52a8\u8054\u901a\u7535\u4fe14G\u624b\u673a', u'weight': 0}], u'code': u'0'}}
<type 'unicode'>
[pid: 12289|app: 0|req: 3/5] 123.157.213.247 () {32 vars in 426 bytes} [Tue Apr 21 01:18:18 2015] GET /api/jdproducts/name/1217499 => generated 133 bytes in 267 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
start working
Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e28da9b0: fetch_product(u'1271596')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e26cd730: fetch_product(u'1271942')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e265b410: fetch_product(u'1271987')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e25decd0: fetch_product(u'12345646')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e2707f50: fetch_product(u'1271680')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e265b5f0: fetch_product(u'1271990')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e26c1050: fetch_product(u'1271881')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e261c4b0: fetch_product(u'1272238')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e261c550: fetch_product(u'1272239')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e2668f50: fetch_product(u'1272055')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e25ded70: fetch_product(u'12345678')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e26cdeb0: fetch_product(u'1271954')> failed with NameError

Traceback (most recent call last):
  File "/home/GitRepo1/yugi/2/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/GitRepo1/yugi/2/app.py", line 262, in fetch_product
    if (now_product.price != price and not(now_priduct.price in ["-1.00","-1"] and price in ["-1.00","-1"])):
NameError: global name 'now_priduct' is not defined
<Greenlet at 0x7ff6e2713190: fetch_product(u'1271708')> failed with NameError

https://api.jd.com/routerjson?v=2.0&method=jingdong.ware.baseproduct.get&app_key=84F0963912EA9D56CD29E8EB3E774A2B&360buy_param_json={%22ids%22:%221217499%22,%22base%22:%22name%22}&timestamp=2015-04-21 01:26:28
{u'jingdong_ware_baseproduct_get_responce': {u'product_base': [{u'sku_id': 1217499, u'name': u'\u82f9\u679c\uff08Apple\uff09iPhone 6 (A1586) 16GB \u91d1\u8272 \u79fb\u52a8\u8054\u901a\u7535\u4fe14G\u624b\u673a', u'weight': 0}], u'code': u'0'}}
<type 'unicode'>
[pid: 12288|app: 0|req: 3/6] 123.157.213.247 () {32 vars in 427 bytes} [Tue Apr 21 01:26:28 2015] GET /api/jdproducts/name/1217499 => generated 133 bytes in 249 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
https://api.jd.com/routerjson?v=2.0&method=jingdong.ware.baseproduct.get&app_key=84F0963912EA9D56CD29E8EB3E774A2B&360buy_param_json={%22ids%22:%221217499%22,%22base%22:%22name%22}&timestamp=2015-04-21 01:26:36
{u'jingdong_ware_baseproduct_get_responce': {u'product_base': [{u'sku_id': 1217499, u'name': u'\u82f9\u679c\uff08Apple\uff09iPhone 6 (A1586) 16GB \u91d1\u8272 \u79fb\u52a8\u8054\u901a\u7535\u4fe14G\u624b\u673a', u'weight': 0}], u'code': u'0'}}
<type 'unicode'>
[pid: 12289|app: 0|req: 4/7] 123.157.213.247 () {32 vars in 426 bytes} [Tue Apr 21 01:26:35 2015] GET /api/jdproducts/name/1217499 => generated 133 bytes in 248 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
